### PR TITLE
Add support for OCaml 4.14

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @UnixJunkie

**Comment by UnixJunkie** [comment]
thanks for the fix

**Comment by UnixJunkie** [comment]
might be of intereset to @vouillon

**Comment by UnixJunkie** [comment]
@kit-ty-kate  tag v1.0.3 includes your fix; I will update the opam package

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-repository/pull/22597

**Pull request merged**
